volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_redis_data: {}
  production_django_media: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: ghcr.io/jvacek/flamerelay-django:latest
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    volumes:
      - production_django_media:/app/flamerelay/media
    ports:
      - '127.0.0.1:8000:5000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: ghcr.io/jvacek/flamerelay-postgres:latest
    volumes:
      - production_postgres_data:/var/lib/postgresql/18/docker
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: docker.io/redis:7.2

    volumes:
      - production_redis_data:/data

  celeryworker:
    <<: *django
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    ports:
      - '127.0.0.1:5556:5555'
    command: /start-flower
