# Generated by Django 4.1.9 on 2023-05-16 10:12

from django.core.exceptions import ValidationError
from django.db import migrations, models


def validate_not_default_value(value):
    if value == "41.123,5.987":
        msg = "Please use the map to drop a pin to where you're making the check-in."
        raise ValidationError(msg)


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_alter_checkin_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkin",
            name="city",
        ),
        migrations.AlterField(
            model_name="checkin",
            name="location",
            field=models.CharField(
                default="41.123,5.987",
                max_length=63,
                validators=[validate_not_default_value],
            ),
        ),
    ]
