# Generated by Django 4.1.9 on 2023-05-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0007_alter_checkin_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="admin_only_checkin",
            field=models.BooleanField(default=False),
        ),
    ]
