# Generated by Django 6.0.4 on 2026-04-13 10:42

import backend.models
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_unit_admin_only_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1024, 1024], upload_to=backend.models.path_and_rename),
        ),
    ]
