# Generated by Django 6.0.4 on 2026-04-20 22:28

import django_resized.forms
from django.db import migrations

import backend.models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0011_alter_checkin_image_webp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkin",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                keep_meta=False,
                null=True,
                quality=85,
                scale=None,
                size=[1024, 1024],
                upload_to=backend.models.path_and_rename,
                validators=[backend.models.validate_image_size],
            ),
        ),
    ]
