# Generated by Django 6.0.4 on 2026-04-27 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0012_alter_checkin_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkin",
            name="unit",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="backend.unit"),
        ),
    ]
