# Generated by Django 6.0.4 on 2026-05-02 23:15

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models

import backend.models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0014_contributor_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckInImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="WEBP",
                        keep_meta=False,
                        quality=85,
                        scale=None,
                        size=[1024, 1024],
                        upload_to=backend.models.path_and_rename,
                        validators=[backend.models.validate_image_size],
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "checkin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="backend.checkin"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
