# Generated by Django 6.0.4 on 2026-04-27 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0014_contributor_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("relay", "Relay"),
                            ("race", "Race"),
                            ("hot_potato", "Hot Potato"),
                            ("distance", "Distance"),
                        ],
                        default="relay",
                        max_length=20,
                    ),
                ),
                (
                    "allowed_time",
                    models.PositiveIntegerField(
                        default=1440, help_text="Time limit for the game in hours. (Distance mode)"
                    ),
                ),
                (
                    "max_gps_drift",
                    models.PositiveIntegerField(
                        default=500,
                        help_text="Maximum allowed GPS drift in meters for check-ins. (Distance+Race modes)",
                    ),
                ),
                (
                    "shelf_life",
                    models.PositiveIntegerField(
                        default=120, help_text="Time in hours before a check-in expires. (Hot Potato mode)"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="unit",
            name="game",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="backend.game"
            ),
        ),
    ]
