# Generated by Django 6.0.4 on 2026-05-02 23:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0016_migrate_checkin_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkin",
            name="image",
        ),
    ]
