# Generated by Django 6.0.4 on 2026-05-04 14:18

from django.db import migrations, models

import backend.models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0020_checkin_finalize_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkin",
            name="message",
            field=models.TextField(blank=True, validators=[backend.models.validate_no_urls]),
        ),
    ]
