# Generated by Django 6.0.4 on 2026-05-04 18:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import backend.models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0022_health_check_periodic_task"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="admin_only_checkin",
            field=models.BooleanField(
                default=False,
                help_text="Whether only admins can check in to this unit, primarily used for demos or for disabling lighters.",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="created_by",
            field=models.ForeignKey(
                help_text="User that created the unit",
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="identifier",
            field=backend.models.CaseInsensitiveCharField(
                help_text="Unique identifier for the unit, e.g. 'alpha-01'. Must start with at least three characters and end with two digits, separated by a dash.",
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Identifier must start with at least three characters", regex="^\\w{3,}"
                    ),
                    django.core.validators.RegexValidator(
                        message="Identifier must end with two digits", regex="\\d{2,}$"
                    ),
                    django.core.validators.RegexValidator(
                        message="Characters and digits must be separated by a dash", regex="^\\w*-\\d*$"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional team that the unit belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backend.team",
            ),
        ),
    ]
