# Generated by Django 6.0.4 on 2026-05-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0024_checkin_anonymous_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="anonymous_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
