CHECKIN_EDIT_GRACE_PERIOD_HOURS = 6
CHECKIN_DELETE_GRACE_PERIOD_HOURS = 6
CHECKIN_DEFAULT_LOCATION = "41.123,5.987"  # PlainLocationField sentinel — filter from globe pins

UNIT_DISTANCE_CACHE_TTL = 60 * 60  # 1 hour

STATS_CACHE_KEY = "api:stats"
STATS_CACHE_TTL = 60 * 5  # 5 minutes

GLOBE_PINS_CACHE_KEY = "api:globe-pins"
GLOBE_PINS_CACHE_TTL = 60 * 10  # 10 minutes
GLOBE_PINS_COUNT = 20

LOGIN_CODE_TIMEOUT_SECONDS = 3 * 60  # 3 minutes

CHECKIN_EMAIL_DELAY_SECONDS = 5 * 60  # 5 minutes — wait before sending so deleted check-ins don't trigger emails
LOGIN_CODE_MAX_ATTEMPTS = 3

CHECKIN_IMAGE_MAX_UPLOAD_BYTES = 10 * 1024 * 1024  # 10 MB

EMAIL_TASK_MAX_RETRIES = 3
EMAIL_TASK_RETRY_BACKOFF_SECONDS = 60
EMAIL_TASK_RETRY_BACKOFF_MAX_SECONDS = 300
