CHECKIN_EDIT_GRACE_PERIOD_HOURS = 6
CHECKIN_DELETE_GRACE_PERIOD_HOURS = 6

UNIT_DISTANCE_CACHE_TTL = 60 * 60  # 1 hour
STATS_CACHE_TTL = 60 * 5  # 5 minutes

LOGIN_CODE_TIMEOUT_SECONDS = 3 * 60  # 3 minutes
LOGIN_CODE_MAX_ATTEMPTS = 3
