#!/bin/bash
# Fetches Cloudflare IP ranges and regenerates cloudflare_ips.conf.
# Run this periodically (e.g. monthly via cron) and reload nginx afterward.
# Suggested crontab entry:
#   0 0 1 * * /etc/nginx/cloudflare_ips/update-cloudflare-ips.sh && nginx -t && systemctl reload nginx

set -euo pipefail

OUTFILE="$(dirname "$0")/cloudflare_ips.conf"
TMPFILE="$(mktemp)"

{
    echo "# Cloudflare IP ranges for ngx_http_realip_module"
    echo "# Generated by update-cloudflare-ips.sh — do not edit manually"
    curl -sf https://www.cloudflare.com/ips-v4/ | sed 's|.*|set_real_ip_from &;|'
    curl -sf https://www.cloudflare.com/ips-v6/ | sed 's|.*|set_real_ip_from &;|'
    echo "real_ip_header CF-Connecting-IP;"
} > "$TMPFILE"

mv "$TMPFILE" "$OUTFILE"
echo "Updated $OUTFILE"
