# Generated by Django 4.1.9 on 2023-05-14 08:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import flamerelay.backend.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "identifier",
                    models.CharField(
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Identifier must start with at least three characters", regex="^\\w{3,}"
                            ),
                            django.core.validators.RegexValidator(
                                message="Identifier must end with two digits", regex="\\d{2,}$"
                            ),
                            django.core.validators.RegexValidator(
                                message="Characters and digits must be separated by a dash", regex="^\\w*-\\d*$"
                            ),
                        ],
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "subscribers",
                    models.ManyToManyField(blank=True, related_name="subscribed_units", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Unit",
                "verbose_name_plural": "Units",
            },
        ),
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=False,
                        null=True,
                        quality=-1,
                        scale=None,
                        size=[1024, 1024],
                        upload_to=flamerelay.backend.models.path_and_rename,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                ("unit", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="backend.unit")),
            ],
            options={
                "ordering": ["date_created"],
            },
        ),
    ]
