# Generated by Django 4.1.9 on 2023-05-16 09:19

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkin",
            name="location",
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
