# Generated by Django 4.1.9 on 2023-05-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkin",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
