# Generated by Django 4.1.9 on 2023-05-16 10:12

from django.db import migrations
import flamerelay.backend.models
import location_field.models.plain


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_alter_checkin_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkin",
            name="city",
        ),
        migrations.AlterField(
            model_name="checkin",
            name="location",
            field=location_field.models.plain.PlainLocationField(
                default="41.123,5.987",
                max_length=63,
                validators=[flamerelay.backend.models.validate_not_default_value],
            ),
        ),
    ]
