# Generated by Django 4.1.9 on 2023-05-19 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_remove_checkin_city_alter_checkin_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.SlugField(max_length=32, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="unit",
            name="team",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="backend.team"
            ),
        ),
    ]
