# Generated by Django 4.1.9 on 2023-05-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_team_unit_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="place",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
