# Generated by Django 4.1.9 on 2023-05-21 19:00

import django.core.validators
from django.db import migrations
import flamerelay.backend.models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_checkin_place"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checkin",
            options={"ordering": ["-date_created"]},
        ),
        migrations.AlterField(
            model_name="unit",
            name="identifier",
            field=flamerelay.backend.models.CaseInsensitiveCharField(
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Identifier must start with at least three characters", regex="^\\w{3,}"
                    ),
                    django.core.validators.RegexValidator(
                        message="Identifier must end with two digits", regex="\\d{2,}$"
                    ),
                    django.core.validators.RegexValidator(
                        message="Characters and digits must be separated by a dash", regex="^\\w*-\\d*$"
                    ),
                ],
            ),
        ),
    ]
